#!/usr/bin/perl

use strict;
use warnings;
use 5.022;
use lib 'lib';
use VectorTracer;

use Data::Dumper;

my $code = join '', <>;

my $tracer = new VectorTracer(debug => 0);
my $node = $tracer->parse($code);
#say Dumper ($node);
say $tracer->trace;


1;
